[2024-09-07T19:20:43.507+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T19:20:43.584+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.transform manual__2024-09-07T19:20:39.469211+00:00 [queued]>
[2024-09-07T19:20:43.794+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.transform manual__2024-09-07T19:20:39.469211+00:00 [queued]>
[2024-09-07T19:20:43.795+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-07T19:20:43.809+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-09-07 19:20:39.469211+00:00
[2024-09-07T19:20:43.817+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=220) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-07T19:20:43.820+0000] {standard_task_runner.py:63} INFO - Started process 222 to run task
[2024-09-07T19:20:43.818+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'transform', 'manual__2024-09-07T19:20:39.469211+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmptkqqt321']
[2024-09-07T19:20:43.820+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask transform
[2024-09-07T19:20:43.886+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.transform manual__2024-09-07T19:20:39.469211+00:00 [running]> on host a319a30e0358
[2024-09-07T19:20:43.996+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T19:20:39.469211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T19:20:39.469211+00:00'
[2024-09-07T19:20:43.998+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T19:20:44.095+0000] {logging_mixin.py:188} INFO -             GEOID     StateName  ... EDU2_kW_ca EDU2_kWh_p
403  9.110416e+09   Connecticut  ...        0.0        0.0
404  9.110462e+09   Connecticut  ...        0.0        0.0
405  9.140406e+09   Connecticut  ...        0.0        0.0

[3 rows x 49 columns]
[2024-09-07T19:20:44.098+0000] {logging_mixin.py:188} INFO - Renamed
[2024-09-07T19:20:44.102+0000] {logging_mixin.py:188} INFO - Keys created
[2024-09-07T19:20:44.104+0000] {logging_mixin.py:188} INFO - keys appended
[2024-09-07T19:20:44.106+0000] {logging_mixin.py:188} INFO - 403                                                                                                                                                                                                                                                                                                                                         s0
404                                                                                                                                                                                                                                                                                                                                         s0
405                                                                                                                                                                                                                                                                                                                                         s0
406                                                                                                                                                                                                                                                                                                                                         s0
407                                                                                                                                                                                                                                                                                                                                         s0
                                                                                                                                                                                                                                                                                                                                            ..
598                                                                                                                                                                                                                                                                                                                                         s0
599                                                                                                                                                                                                                                                                                                                                         s0
600                                                                                                                                                                                                                                                                                                                                         s0
601                                                                                                                                                                                                                                                                                                                                         s0
199\t9110502700\t Connecticut\t Capitol Planning Region\tCensus Tract 5027\t1011637\t0\t1\t0\t4\t100\t0\t1\t10\t100\tMiddle third\t45\t3\t9661.516\t63\t15.317\tUpper third\t89\t0\t3823.465\t11\t10.327\t5074\t42.04\t13.99\t33.84\t5.52\t0.06\t4.55\t30423\t30.2\t8.8\t97.2\t4\t586\t718977\t0\t0\t0\t5\t1447\t1775545\t1\t215\t263761    s1
Name: s_name, Length: 200, dtype: object
[2024-09-07T19:20:44.112+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_scripts/***_pipeline.py:64: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TractRecords_fct['state_id'] = clean_batch['s_name'].apply(lambda x: state_dict.get(x))

[2024-09-07T19:20:44.118+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T19:20:44.119+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2024-09-07/processed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 96, in transform_data
    Path(target_dir).mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1315, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/2024-09-07'
[2024-09-07T19:20:44.133+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=transform, run_id=manual__2024-09-07T19:20:39.469211+00:00, execution_date=20240907T192039, start_date=20240907T192043, end_date=20240907T192044
[2024-09-07T19:20:44.149+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task transform ([Errno 13] Permission denied: '/opt/airflow/data/2024-09-07'; 222)
[2024-09-07T19:20:44.196+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-07T19:20:44.233+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T19:20:44.238+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
