[2024-09-03T17:40:28.967+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: solar_adoption_dag.load_County_dim manual__2024-09-03T17:40:26.117727+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
